### ISSUE TITLE
make improvement in Color class 🎉

### ISSUE THREAD

**Issue by kalevski** [disgraded/gdxmachine#2]
Override + operator in the Color class for easily adding 2 color classes. The output must be a new instance.
If you are confused with the description feel free to comment

**Comment by Hiosdra** [comment]
Hi, I will try to do that

**Comment by Hiosdra** [comment]
I have added this functionality, but there is no test directory in project. Can I add test framework? Do you have any preferences about which to choose?

**Comment by kalevski** [comment]
@Hiosdra  first of all thanks, :+1: 
will be nice if you do that, I will open new issue for the test framework
