### ISSUE TITLE
Change the android icon (mipmap)

### ISSUE THREAD

**Issue by kalevski** [disgraded/gdxmachine#27]
Generate mipmaps from the following image
and replace them with the current mipmaps
**IMAGE:**
![gdxmachine logo](https://user-images.githubusercontent.com/10467454/65911921-ae162b00-e3cd-11e9-912a-ba8b7ed4e7be.png)

**Comment by dotvhs** [comment]
I can prepare those icons for you in all versions + new Adaptive Icons and Play Store icon.

**Comment by kalevski** [comment]
Thank you :100: :smile:
