### ISSUE TITLE
add dokka as a documentation engine

### ISSUE THREAD

**Issue by kalevski** [disgraded/gdxmachine#4]
Dokka repo: https://github.com/Kotlin/dokka

**Comment by ThinkHattke** [comment]
@kalevski can I work on this?

**Comment by kalevski** [comment]
yes, thanks :smile:

**Comment by ThinkHattke** [comment]
@kalevski what format should the documentation should be in?

**Comment by kalevski** [comment]
You ask me about output format or ? @ThinkHattke

**Comment by kalevski** [comment]
markdown is okay I think @ThinkHattke
