### ISSUE TITLE
implement asset type "PlainText" in Resource Module

### ISSUE THREAD

**Issue by kalevski** [disgraded/gdxmachine#5]
Skills required: [libGDX](https://libgdx.badlogicgames.com/)
NOTICE: If you are enthusiast read the documentation for resource management [click here](https://github.com/libgdx/libgdx/wiki/Managing-your-assets)

You need to implement Asynchronous Asset Loader for reading files as plain text and method in AssetPackage class as helper for easily locating the file and fetching the content

**Comment by Batanick** [comment]
This might be closed now

**Comment by Batanick** [comment]
Bug reported here: https://github.com/disgraded/gdxmachine/issues/32
