### ISSUE TITLE
hexcolor validation in Color class 🙈

### ISSUE THREAD

**Issue by kalevski** [disgraded/gdxmachine#6]
Color#set method at the moment checks only for first character of the string and length of the string.
Validation will pass if you try to set invalid hex color code as #ZZJKHG.
Implement better validation.

**Comment by mstieranka** [comment]
Can I work on this?

**Comment by kalevski** [comment]
Yeah, thanks

**Comment by mstieranka** [comment]
I implemented this validation, if a test framework gets added down the line, I could also add tests of this functionality.

**Comment by kalevski** [comment]
tomorrow I will implement test framework & headless platform for testing, can I assign a new issue on you for testing the feature ?

**Comment by mstieranka** [comment]
Sure, I'll definitely take a look at it.
